"""Persistence: SQLite locally, Postgres (Supabase) when DATABASE_URL is set.

The app writes plain SQL with ``?`` placeholders; the Postgres backend
translates them. Keeping one dialect-light SQL surface avoids an ORM.
"""

from __future__ import annotations

import json
import os
import sqlite3
import threading
from contextlib import contextmanager

SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS campaigns (
    id INTEGER PRIMARY KEY,
    owner_id TEXT NOT NULL DEFAULT 'local',
    name TEXT NOT NULL,
    website TEXT, description TEXT,
    sender_name TEXT, sender_email TEXT, sender_company TEXT, postal_address TEXT,
    booking_link TEXT, crm_webhook TEXT,
    daily_cap INTEGER DEFAULT 30, mailbox_age_days INTEGER DEFAULT 0,
    autopilot INTEGER DEFAULT 0, autopilot_min_score INTEGER DEFAULT 85,
    icp TEXT, status TEXT DEFAULT 'draft',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS prospects (
    id INTEGER PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    company TEXT, website TEXT, domain TEXT,
    contact_name TEXT, contact_title TEXT, email TEXT, email_status TEXT,
    why_fit TEXT, signals TEXT, fit_score INTEGER, source TEXT,
    status TEXT DEFAULT 'new',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campaign_id, domain, email)
);
CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    kind TEXT DEFAULT 'initial',          -- initial | followup | reply
    step INTEGER DEFAULT 0, wait_days INTEGER DEFAULT 0,
    subject TEXT, body TEXT, hook TEXT, warnings TEXT,
    status TEXT DEFAULT 'pending_review', -- pending_review | approved | rejected | sent | skipped
    sent_at TEXT, sent_via TEXT,          -- smtp | dry_run
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS replies (
    id INTEGER PRIMARY KEY,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    body TEXT, intent TEXT, summary TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS suppression (
    email TEXT PRIMARY KEY, reason TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS ledger (
    id INTEGER PRIMARY KEY,
    campaign_id INTEGER, action TEXT, credits INTEGER, note TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
"""

# Same shape for Postgres. Applied as a Supabase migration (see supabase/migrations);
# also run on startup with IF NOT EXISTS so a fresh database works out of the box.
POSTGRES_SCHEMA = (
    SQLITE_SCHEMA.replace("id INTEGER PRIMARY KEY", "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace("campaign_id INTEGER", "campaign_id BIGINT")
    .replace("prospect_id INTEGER", "prospect_id BIGINT")
)

JSON_COLUMNS = {"icp", "signals", "warnings"}


class DB:
    def __init__(self, path: str | None = None, url: str | None = None):
        self.url = url or (None if path else os.environ.get("DATABASE_URL"))
        self.pg = bool(self.url)
        self.path = path or os.environ.get("PIPEWRIGHT_DB", "pipewright.db")
        self._lock = threading.RLock()
        self._conn = None
        if self.pg:
            if os.environ.get("PIPEWRIGHT_SKIP_MIGRATE") != "1":
                self._run_script(POSTGRES_SCHEMA)
        else:
            self._run_script(SQLITE_SCHEMA)

    # -- connection handling --------------------------------------------------

    def _connect(self):
        if self.pg:
            import psycopg
            from psycopg.rows import dict_row

            # prepare_threshold=None keeps us compatible with Supabase's transaction pooler.
            return psycopg.connect(self.url, row_factory=dict_row, prepare_threshold=None, connect_timeout=10)
        conn = sqlite3.connect(self.path, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        return conn

    @property
    def conn(self):
        if self._conn is None or (self.pg and self._conn.closed):
            self._conn = self._connect()
        return self._conn

    def _sql(self, sql: str) -> str:
        return sql.replace("?", "%s") if self.pg else sql

    def _run_script(self, script: str) -> None:
        with self.tx() as c:
            if self.pg:
                c.execute(script)
            else:
                c.executescript(script)

    @contextmanager
    def tx(self):
        with self._lock:
            conn = self.conn
            try:
                yield conn
                conn.commit()
            except Exception:
                conn.rollback()
                if self.pg and not conn.closed and conn.broken:
                    self._conn = None
                raise

    def _execute(self, sql: str, params: tuple = ()):
        """Run a statement and return the cursor, reconnecting once if the pooled link dropped."""
        for attempt in (0, 1):
            try:
                with self._lock:
                    cur = self.conn.execute(self._sql(sql), params)
                    if self.pg:
                        self.conn.commit()
                    return cur
            except Exception as e:
                if self.pg and attempt == 0 and type(e).__name__ in ("OperationalError", "InterfaceError"):
                    self._conn = None
                    continue
                if self.pg and self._conn is not None and not self._conn.closed:
                    self._conn.rollback()
                raise

    # -- generic helpers --------------------------------------------------------

    @staticmethod
    def _encode(values: dict) -> dict:
        out = {}
        for k, v in values.items():
            if k in JSON_COLUMNS and v is not None:
                v = json.dumps(v)
            elif isinstance(v, bool):  # INTEGER flag columns on both backends
                v = int(v)
            out[k] = v
        return out

    @staticmethod
    def row(r) -> dict | None:
        if r is None:
            return None
        d = dict(r)
        for k in JSON_COLUMNS & d.keys():
            if isinstance(d[k], str):
                try:
                    d[k] = json.loads(d[k])
                except ValueError:
                    pass
        return d

    def insert(self, table: str, values: dict, ignore_conflict: bool = False) -> int | None:
        values = self._encode(values)
        cols = ", ".join(values)
        marks = ", ".join("?" for _ in values)
        conflict = " ON CONFLICT DO NOTHING" if ignore_conflict else ""
        with self.tx() as c:
            row = c.execute(self._sql(f"INSERT INTO {table} ({cols}) VALUES ({marks}){conflict} RETURNING id"),
                            list(values.values())).fetchone()
        if row is None:
            return None
        return row["id"] if self.pg else row[0]

    def update(self, table: str, row_id: int, values: dict) -> None:
        if not values:
            return
        values = self._encode(values)
        sets = ", ".join(f"{k} = ?" for k in values)
        self.execute(f"UPDATE {table} SET {sets} WHERE id = ?", (*values.values(), row_id))

    def execute(self, sql: str, params: tuple = ()) -> None:
        with self.tx() as c:
            c.execute(self._sql(sql), params)

    def get(self, table: str, row_id: int) -> dict | None:
        return self.row(self._execute(f"SELECT * FROM {table} WHERE id = ?", (row_id,)).fetchone())

    def all(self, sql: str, params: tuple = ()) -> list[dict]:
        return [self.row(r) for r in self._execute(sql, params).fetchall()]

    def one(self, sql: str, params: tuple = ()):
        r = self._execute(sql, params).fetchone()
        if r is None:
            return None
        return next(iter(dict(r).values())) if self.pg else r[0]

    def pairs(self, sql: str, params: tuple = ()) -> dict:
        """Two-column query -> dict (e.g. status -> count)."""
        out = {}
        for r in self._execute(sql, params).fetchall():
            key, value = list(dict(r).values())[:2]
            out[key] = value
        return out

    # -- domain helpers -----------------------------------------------------

    def is_suppressed(self, email: str) -> bool:
        return bool(self.one("SELECT 1 FROM suppression WHERE email = ?", (email.lower(),)))

    def suppress(self, email: str, reason: str) -> None:
        with self.tx() as c:
            c.execute(self._sql("INSERT INTO suppression (email, reason) VALUES (?, ?) ON CONFLICT DO NOTHING"),
                      (email.lower(), reason))

    def charge(self, campaign_id: int | None, action: str, credits: int, note: str = "") -> None:
        self.insert("ledger", {"campaign_id": campaign_id, "action": action, "credits": credits, "note": note})
