-- Pipewright schema for Supabase Postgres.
-- The FastAPI backend connects with the database connection string (it bypasses RLS).
-- RLS is enabled with no policies, so the public anon/authenticated API roles
-- cannot read or write these tables through Supabase's REST API.
CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL DEFAULT 'local',
    name TEXT NOT NULL,
    website TEXT, description TEXT,
    sender_name TEXT, sender_email TEXT, sender_company TEXT, postal_address TEXT,
    booking_link TEXT, crm_webhook TEXT,
    daily_cap INTEGER DEFAULT 30, mailbox_age_days INTEGER DEFAULT 0,
    autopilot INTEGER DEFAULT 0, autopilot_min_score INTEGER DEFAULT 85,
    icp TEXT, status TEXT DEFAULT 'draft',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS prospects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    company TEXT, website TEXT, domain TEXT,
    contact_name TEXT, contact_title TEXT, email TEXT, email_status TEXT,
    why_fit TEXT, signals TEXT, fit_score INTEGER, source TEXT,
    status TEXT DEFAULT 'new',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (campaign_id, domain, email)
);
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    prospect_id BIGINT NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    kind TEXT DEFAULT 'initial',          -- initial | followup | reply
    step INTEGER DEFAULT 0, wait_days INTEGER DEFAULT 0,
    subject TEXT, body TEXT, hook TEXT, warnings TEXT,
    status TEXT DEFAULT 'pending_review', -- pending_review | approved | rejected | sent | skipped
    sent_at TEXT, sent_via TEXT,          -- smtp | dry_run
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prospect_id BIGINT NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    body TEXT, intent TEXT, summary TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS suppression (
    email TEXT PRIMARY KEY, reason TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT, action TEXT, credits INTEGER, note TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS campaigns_owner_idx ON campaigns (owner_id);
CREATE INDEX IF NOT EXISTS prospects_campaign_idx ON prospects (campaign_id);
CREATE INDEX IF NOT EXISTS prospects_email_idx ON prospects (email);
CREATE INDEX IF NOT EXISTS messages_campaign_status_idx ON messages (campaign_id, status);
CREATE INDEX IF NOT EXISTS messages_prospect_idx ON messages (prospect_id);
CREATE INDEX IF NOT EXISTS replies_prospect_idx ON replies (prospect_id);
CREATE INDEX IF NOT EXISTS ledger_campaign_idx ON ledger (campaign_id);

ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE prospects ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppression ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger ENABLE ROW LEVEL SECURITY;
